server:
  port: 9000

spring:
  applicaton:
    name: api

#Mysql conf
  datasource:
    url: jdbc:mysql://localhost:3306/noeldb
    username: root
    password: root

#Jpa conf
  jpa:
    hibernate:
      ddl-auto: update
